apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: Netflix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Netflix
  template:
    metadata:
      labels:
        app: Netflix
    spec:
      containers:
        - name: Netflix
          image: seifseddik120/netflix-2024:${BUILD_NUMBER}
          ports:
            - containerPort: 80
